name: docker-based library testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: the-virtual-brain
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: multiscale
          dockerfile: tvb_build/docker/Dockerfile-multiscale-build
      - name: run something in the built image
        run: >
          docker run
          -v $PWD:/work -w /work/scientific_library
          docker.pkg.github.com/the-virtual-brain/tvb-root/multiscale
          pytest -Wignore -n4
