name: docker-based library testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: cd scientific_library && docker build -t tvb/lib .

      - name: Run tests
        run: >
          docker run --rm -v $PWD/scientific_library:/tvb/lib -w /tvb/lib tvb/lib
          pytest -n 4
