name: docker-based library testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build -f scientific_library/Dockerfile -t tvb/lib-ci scientific_library

      - name: Run tests
        run: >
          docker run --rm -v $PWD:/work -w /work/scientific_library tvb/lib-ci 
          pytest -Wignore --profile-svg

      - name: archive test profiles
        uses: actions/upload-artifact@v2
        with:
          name: test-profile.svg
          path: scientific_library/prof/combined.svg

